### ISSUE TITLE
Footer is hiding buttons

### ISSUE THREAD

**Issue by AadershChaubey** [nibble-4bits/Sudoku-Solver-Visualizer#12]
![image](https://user-images.githubusercontent.com/69140691/114036040-90344c80-9834-11eb-9739-b4902290f0d0.png)

changing footer's position to relative will work it out

**Comment by nibble-4bits** [comment]
Good catch @AadershChaubey ! I had not noticed that `position: absolute` would not work in small resolution screens

Thanks for pointing out the issue and I'll be working on the fix soon 👍
